name: action.yml demo
 
on:
  issue_comment:
    types: [created, deleted]
  issues:
    types: [opened, edited, milestoned]
       
jobs:
  # demo1: OpenSfhit Secret 更新
  openshift-update:
    runs-on: [self-hosted]
    name: openshift
    steps:
      # step1: 通过 Action, 使用 PAM 查询密码
      - id: step1
        name: username password obtain
        uses: shterm/pam-obtain@v1
        with:
          app-id: "test"
          user-name: "root"
          asset-name: "resource"
          connect-host: "10.13.1.2"
          credential: ${{ secrets.PAM_TOKEN }}
      # step2: 通过 env.password 使用查询的密码
      - id: step2
        name: 修改 openshift 的 secret 值
        run: >
          oc create secret generic hello-world
          --from-literal=username=hello
          --from-literal=password=${{ env.password }}
          --dry-run=client -o yaml -n default | oc replace -f -
